# Generated by Django 3.2.6 on 2023-12-14 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_alter_ad_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
    ]
